// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwrbsNKIwQ1GDl1NZh27lCXXU77uU-3TU',
    appId: '1:169260736222:web:83b14c9095c12324e8ac4f',
    messagingSenderId: '169260736222',
    projectId: 'minal-6ede8',
    authDomain: 'minal-6ede8.firebaseapp.com',
    storageBucket: 'minal-6ede8.firebasestorage.app',
    measurementId: 'G-58V220VHXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqq-d1nYKZd49kqVA7vZBCGNcBT4DEjpo',
    appId: '1:169260736222:android:dde26e2a9c174b13e8ac4f',
    messagingSenderId: '169260736222',
    projectId: 'minal-6ede8',
    storageBucket: 'minal-6ede8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtKbhqbWy_6h5HIfwsfjXQFgQ1TnmA4pU',
    appId: '1:169260736222:ios:1247d6b7b4baaf43e8ac4f',
    messagingSenderId: '169260736222',
    projectId: 'minal-6ede8',
    storageBucket: 'minal-6ede8.firebasestorage.app',
    iosBundleId: 'com.example.fypRupisafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtKbhqbWy_6h5HIfwsfjXQFgQ1TnmA4pU',
    appId: '1:169260736222:ios:1247d6b7b4baaf43e8ac4f',
    messagingSenderId: '169260736222',
    projectId: 'minal-6ede8',
    storageBucket: 'minal-6ede8.firebasestorage.app',
    iosBundleId: 'com.example.fypRupisafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwrbsNKIwQ1GDl1NZh27lCXXU77uU-3TU',
    appId: '1:169260736222:web:071000f38a23ac2ae8ac4f',
    messagingSenderId: '169260736222',
    projectId: 'minal-6ede8',
    authDomain: 'minal-6ede8.firebaseapp.com',
    storageBucket: 'minal-6ede8.firebasestorage.app',
    measurementId: 'G-YE7R461CMM',
  );
}
